 spring.application.name=ThymeleafSecurity
#spring.application.user.name= Shruti
#spring.application.password=Shruti

server.port=8080

#JDBC Properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=Shruti@24